# Generated by Django 3.1.6 on 2021-04-14 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='')),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('Degree', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('married', 'married'), ('single', 'single')], max_length=100, null=True)),
                ('fellowship', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_papers', models.IntegerField(blank=True, default=0, null=True)),
                ('notable_work', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('working', models.ManyToManyField(blank=True, to='research.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('graduation_year', models.DateField(blank=True, null=True)),
                ('Degree', models.CharField(blank=True, max_length=100, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('certificate_title', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_description', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_url', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_issue', models.DateField(blank=True, null=True)),
                ('certificate_expire', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('working', models.ManyToManyField(blank=True, to='research.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('stall', 'stall'), ('ongoing', 'ongong'), ('finished', 'finished')], default='ongoing', max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('mentors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.professor')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.student')),
            ],
        ),
    ]
