# Generated by Django 3.1.6 on 2021-04-16 13:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20210415_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=100, null=True),
        ),
    ]
