# Generated by Django 3.1.6 on 2021-04-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20210416_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='certificate_ID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certificate_description',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certificate_expire',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certificate_issue',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certificate_organisation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certificate_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certificate_url',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_description', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_url', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_issue', models.DateField(blank=True, null=True)),
                ('certificate_expire', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.student')),
            ],
        ),
    ]
